### ISSUE TITLE
Check minimal template for HTML shortcut

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/judge-html#155]
Non-partial exercises will almost always have this minimal template:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    
</body>
</html>
```

I wrote an `evaluator. py` (Emmet and regular) for it and I would like a shortcut for it. How is up for discussion, suggestions are welcome. Some suggestions:

**Syntax:**
* `html = HtmlSuite(content, minimal_template=True)`

**Visually:**
I would like some visual distinction from the checks asked in the exercise. The mentioned minimal template should be there, but isn't the main focus of the exercise.
* One check, with multiple subchecks
![image](https://user-images.githubusercontent.com/56451049/136383992-089bb86f-768d-469f-b298-83d00f11292e.png)
* (Separate tab/suite)

## `evaluator.py`
- Emmet

```python
def create_suites(content: str) -> list[TestSuite]:
    html = HtmlSuite(content)

    html.make_item('The document coding is specified', html.has_doctype())

    html.make_item_from_emmet("<html> has a language attribute",
                              'html[lang="DUMMY"]')

    html.make_item_from_emmet("Inside the <html> tag is the <head> tag",
                              "html>head")

    html.make_item_from_emmet("Inside the <head> tag is the <title> tag",
                              "head>title")

    html.make_item_from_emmet("The <title> tag has content",
                              "title{DUMMY}")

    html.make_item_from_emmet("Inside the <head> tag is the <meta> tag",
                              "head>meta")

    html.make_item_from_emmet("<meta> has the 'UTF-8' charset attribute",
                              "meta[charset='UTF-8']")  # TODO case insensitive option

    html.make_item_from_emmet("Inside the <html> tag is the <body> tag",
                              "html>body")

    html.translations["nl"] = [
        "De document codering is gespecifieerd",
        "<html> heeft een taal attribuut",
        "Binnen de <html> tag zit de <head> tag",
        "Binnen de <head> tag zit de <title> tag",
        "De <title> tag bevat tekst",
        "Binnen de <head> tag zit de <meta> tag",
        "<meta> heeft het UTF-8 charset attribuut",
        "Binnen de <html> tag zit de <body> tag"
    ]

    return [html]
```

- Regular

```python
def create_suites(content: str) -> list[TestSuite]:
    html = HtmlSuite(content)

    el_html = html.element("html")
    el_head = el_html.get_child("head")
    # el_meta = html.element("html>head>meta") # Same but different syntax
    # el_meta = html.get_child('head').get_child('meta') # Same but different syntax
    el_meta = el_head.get_child('meta')
    # el_title = html.element("html>head>title") # Same but different syntax
    el_title = el_head.get_child("title")
    el_body = el_html.get_child("body")

    html.make_item('The document coding is specified', html.has_doctype())

    html.make_item("<html> has a language attribute",
                   el_html.attribute_exists('lang'))

    html.make_item("Inside the <html> tag is the <head> tag",
                   el_head.exists())

    html.make_item("Inside the <head> tag is the <title> tag",
                   el_title.exists())

    html.make_item("The <title> tag has content",
                   html.element('title').has_content())

    html.make_item("Inside the <head> tag is the <meta> tag",
                   el_meta.exists())

    html.make_item("<meta> has the 'UTF-8' charset attribute",
                   html.element('meta', charset=True).attribute_exists('charset', "UTF-8", case_insensitive=True))

    html.make_item("Inside the <html> tag is the <body> tag",
                   el_body.exists())

    html.translations["nl"] = [
        "De document codering is gespecifieerd",
        "<html> heeft een taal attribuut",
        "Binnen de <html> tag zit de <head> tag",
        "Binnen de <head> tag zit de <title> tag",
        "De <title> tag bevat tekst",
        "Binnen de <head> tag zit de <meta> tag",
        "<meta> heeft het UTF-8 charset attribuut",
        "Binnen de <html> tag zit de <body> tag"
    ]

    return [html]
```

**Comment by stijndcl** [comment]
This layout is _possible_, even though the implementation is a bit hacky, but doing it like this students can't tell which check failed. The line on the left is for the entire TestCase, not the Tests inside of it. If one of them fails, the entire TestCase is marked as wrong. Though I'm against making this a separate tab, I feel like that would be quite overkill.

![image](https://user-images.githubusercontent.com/60451863/142014841-769de4f4-f18c-4b84-a832-7caa8a29aadf.png)

**Comment by BTWS2** [comment]
Hmm, that's true. Both options are not ideal. Students should see which one of the template checks failed. I assume a separate tab would mean a duplicate validation check?

I added the minimal examples to the example repository because it shows how the judge works and will come in handy if teachers need it.

Another option is to integrate these tests in the judge. `html = HtmlSuite(content, minimal_template=True)` would add these tests to the top of the list (after HTML validation) as if the teacher wrote it. This would be individual checks (not the grouped lay-out). What's your opinion on this?

**Comment by stijndcl** [comment]
> I assume a separate tab would mean a duplicate validation check?

Yes, indeed.

> This would be individual checks (not the grouped lay-out). What's your opinion on this?

That's an option, but then the exercise already has like 10-ish Checks that display to a student _before_ the exercise's own Checks, it adds a massive wall of text/Checks to the submission.

A solution could maybe be to make a Check like the screenshot I sent above, but only displaying the messages of the failing tests?

**Comment by BTWS2** [comment]
> A solution could maybe be to make a Check like the screenshot I sent above, but only displaying the messages of the failing tests?

Good idea! To be clear, the non-Emmet syntax should be used (case insensitive option isn't available for Emmet) and the displayed text should be changed to negative (e.g. The document coding isn't specified).
