### ISSUE TITLE
For loop (with zip) false positive

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/judge-html#191]
- [ ] https://naos.ugent.be/nl/submissions/982946/
https://github.ugent.be/brewille/oef_websites/blob/master/docs_examples/ugent_faculty_websites/evaluation/evaluator.py

The checks with for-loops result in false positives. The element doesn't exist, so it should be false or I'm missing something.

**Comment by stijndcl** [comment]
If you use `zip`, it keeps going until either one of the lists is exhausted. So zipping an empty list with something results in an empty list. Similarly, the list comprehension will result in an empty list.

Seeing as `li` is empty (judging by the submission), all of your list comprehensions and for-loops do nothing, so none of them contain failing tests, so these functions return `True`.
