### ISSUE TITLE
CSS validation error if html tag is missing

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/judge-html#209]
- [ ] https://naos.dodona.be/en/submissions/983159/
![image](https://user-images.githubusercontent.com/56451049/152750531-259fe814-5873-420d-bcef-9dcae2fb6a68.png)

**Comment by stijndcl** [comment]
Should this case be counted as "invalid html", or should we wrap it in an html tag ourselves?

**Comment by BTWS2** [comment]
```python
from bs4 import BeautifulSoup

print(BeautifulSoup("<head></head><body></body>", "lxml")) # <html><head></head><body></body></html>
print(BeautifulSoup("<head></head><body></body>", "html5lib")) # <html><head></head><body></body></html>
print(BeautifulSoup("<head></head><body></body>", "html.parser")) # <head></head><body></body>
```
https://www.crummy.com/software/BeautifulSoup/bs4/doc/#differences-between-parsers

I'm leaning towards Python’s built-in HTML parser approach and don't let the judge add the `html` tag. The `html` tag isn't necessary, but I think it's best students adhere to the `html`, `head`, `body` structure. I wouldn't expect the judge to add the html tag, but the tests involving the html tag to fail.

The code I'm using to evaluate is located here: https://github.ugent.be/brewille/oef_websites/blob/master/css-exercises/missing_tags/evaluation/evaluator.py
